"""added suggestion table

Revision ID: 02388c08dcb2
Revises: e308ad6026ac
Create Date: 2021-05-16 20:35:40.624635

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '02388c08dcb2'
down_revision = 'e308ad6026ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestion'))
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_suggestion_id_suggestion'), 'suggestion', ['suggestion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_suggestion_id_suggestion'), type_='foreignkey')
        batch_op.drop_column('suggestion_id')


    op.drop_table('suggestion')
    # ### end Alembic commands ###
