"""added unique to comms

Revision ID: 0801537eefe1
Revises: 755e6e328fcf
Create Date: 2021-11-15 00:05:18.946417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0801537eefe1'
down_revision = '755e6e328fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('comms', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_comms_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_comms_user_id'), type_='unique')

    # ### end Alembic commands ###
