"""changed highlight position column 

Revision ID: 0d0110b0c58a
Revises: e07ab0ac88a8
Create Date: 2020-11-27 15:23:57.439388

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '0d0110b0c58a'
down_revision = 'e07ab0ac88a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)

    # ### end Alembic commands ###
