"""backref on article

Revision ID: 13646429f5da
Revises: 785a5e945438
Create Date: 2021-03-22 22:25:53.913326

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '13646429f5da'
down_revision = '785a5e945438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass    

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
