"""empty message

Revision ID: 18674b6e64b3
Revises: da4b4a0ed3d2
Create Date: 2020-06-12 13:16:34.078492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18674b6e64b3'
down_revision = 'da4b4a0ed3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('highlights_topics', 'highlight_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('highlights_topics', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('firstname', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_column('user', 'firstname')
    op.alter_column('highlights_topics', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('highlights_topics', 'highlight_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
