"""removed unique constraint from topic title

Revision ID: 1c8bac41ee45
Revises: 7fe237d21a13
Create Date: 2020-10-12 19:26:54.241505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8bac41ee45'
down_revision = '7fe237d21a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_title')
        batch_op.create_index(batch_op.f('ix_topic_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_title'))
        batch_op.create_index('ix_topic_title', ['title'], unique=1)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
