"""added uuid to highlight

Revision ID: 202c385e6984
Revises: 8287a55072a2
Create Date: 2023-02-01 08:02:50.281409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "202c385e6984"
down_revision = "8287a55072a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlight", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlight", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
