"""empty message

Revision ID: 21c82ee44b00
Revises: 18674b6e64b3
Create Date: 2020-06-12 13:31:47.979661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c82ee44b00'
down_revision = '18674b6e64b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_highlight_note'), 'highlight', ['note'], unique=False)
    op.add_column('user', sa.Column('firstname', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_column('user', 'firstname')
    op.drop_index(op.f('ix_highlight_note'), table_name='highlight')
    # ### end Alembic commands ###
