"""added uuid to tag

Revision ID: 26b62ee75c23
Revises: 5e2af35aa067
Create Date: 2023-02-05 00:09:59.861431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26b62ee75c23"
down_revision = "5e2af35aa067"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
