"""empty message

Revision ID: 294aec5ede40
Revises: 638d4dada82c
Create Date: 2020-06-12 14:08:42.240484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294aec5ede40'
down_revision = '638d4dada82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=False)
        batch_op.drop_index('ix_user_first_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('first')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_user_first_name', ['first_name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_user_firstname'))

    # ### end Alembic commands ###
