"""added article by email field to user

Revision ID: 393f58b9d190
Revises: 668dc63d3f6d
Create Date: 2021-04-10 22:44:12.110313

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '393f58b9d190'
down_revision = '668dc63d3f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_by_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('add_by_email')

    # ### end Alembic commands ###
