"""added highlightedtextJSON to article model - now can store highlights in db and reload on web refresh.

Revision ID: 3b111d8bca85
Revises: d122055e9a24
Create Date: 2020-06-25 11:21:38.658497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b111d8bca85'
down_revision = 'd122055e9a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlightedTextJSON', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('highlightedTextJSON')

    # ### end Alembic commands ###
