"""added processing field

Revision ID: 4796cfdbe050
Revises: 35127e9854c7
Create Date: 2023-01-19 21:59:43.129089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4796cfdbe050"
down_revision = "35127e9854c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.add_column(sa.Column("processing", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.drop_column("processing")

    # ### end Alembic commands ###
