"""adding index on article title lowercase

Revision ID: 50e2f2ff2dbd
Revises: a544d948cd1b
Create Date: 2021-11-29 00:35:22.478120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e2f2ff2dbd'
down_revision = 'a544d948cd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index('articles_lower_title_key', [sa.text('lower(title)')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('articles_lower_title_key')

    # ### end Alembic commands ###
