"""added progress and done columns to article model 


Revision ID: 58f30d8ff1d0
Revises: 72f7b3154cf7
Create Date: 2020-09-05 15:09:53.349125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f30d8ff1d0'
down_revision = '72f7b3154cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_progress'), ['progress'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_progress'))
        batch_op.drop_column('progress')
        batch_op.drop_column('done')

    # ### end Alembic commands ###
