"""added article_count and highlight_count to tags

Revision ID: 5e2af35aa067
Revises: e5f879371002
Create Date: 2023-02-04 23:53:23.449712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e2af35aa067"
down_revision = "e5f879371002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(sa.Column("highlight_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("article_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("article_count")
        batch_op.drop_column("highlight_count")
    # ### end Alembic commands ###
