"""changed article url to article source

Revision ID: 615e34de5588
Revises: 3781f53962d3
Create Date: 2020-06-17 13:29:33.898305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615e34de5588'
down_revision = '3781f53962d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=500), nullable=True))
        batch_op.drop_index('ix_article_title')
        batch_op.drop_index('ix_article_unread')
        batch_op.drop_column('unread')
        batch_op.drop_column('url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('unread', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_article_unread', ['unread'], unique=False)
        batch_op.create_index('ix_article_title', ['title'], unique=False)
        batch_op.drop_column('source')

    # ### end Alembic commands ###
