"""empty message

Revision ID: 638d4dada82c
Revises: db917a433d28
Create Date: 2020-06-12 14:00:42.392611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638d4dada82c'
down_revision = 'db917a433d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    #op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    #op.drop_index('ix_user_first', table_name='user')
    #op.drop_column('user', 'firstname')
    #op.drop_column('user', 'first')
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(), nullable=True))
    op.create_index('ix_user_first', 'user', ['first'], unique=False)
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
