"""added no_topics bool to Highlights

Revision ID: 668dc63d3f6d
Revises: 13646429f5da
Create Date: 2021-03-27 23:05:01.715751

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '668dc63d3f6d'
down_revision = '13646429f5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_topics', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_highlight_no_topics'), ['no_topics'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlight_no_topics'))
        batch_op.drop_column('no_topics')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)

    # ### end Alembic commands ###
