"""reset db migrations

Revision ID: 6c9a91a335e5
Revises: c10add650dd1
Create Date: 2020-06-25 14:09:07.033693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9a91a335e5'
down_revision = 'c10add650dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlightedText', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('highlightedText')

    # ### end Alembic commands ###
