"""bookmarks json, article mapped col

Revision ID: 6e7be7a417b3
Revises: 9f51a676d529
Create Date: 2026-02-06 14:25:38.370280

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6e7be7a417b3"
down_revision = "9f51a676d529"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Clean up orphaned articles with NULL user_id before adding NOT NULL constraint
    op.execute("DELETE FROM article WHERE user_id IS NULL")

    # Convert bookmarks from VARCHAR to JSONB with proper parsing
    # Handle NULL, empty string, and valid JSON string formats
    op.execute(
        """
        ALTER TABLE article
        ALTER COLUMN bookmarks TYPE jsonb
        USING CASE
            WHEN bookmarks IS NULL THEN NULL
            WHEN bookmarks = '' THEN '[]'::jsonb
            ELSE bookmarks::jsonb
        END
    """
    )
    op.execute("UPDATE article SET notes = '' WHERE notes IS NULL")
    op.execute("UPDATE article SET reflections = '' WHERE reflections IS NULL")
    op.execute("UPDATE article SET processing = false WHERE processing IS NULL")

    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.alter_column("uuid", existing_type=sa.UUID(), nullable=False)
        batch_op.alter_column("unread", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("title", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("archived", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("progress", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
        batch_op.alter_column("done", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("notes", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("reflections", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("processing", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("highlights_topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_highlights_topics_topic_id"))

    with op.batch_alter_table("tags_articles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_articles_article_id"), ["article_id"], unique=False)

    with op.batch_alter_table("tags_highlights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_highlights_tag_id"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags_highlights", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_highlights_tag_id"), ["tag_id"], unique=False)

    with op.batch_alter_table("tags_articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_articles_article_id"))

    with op.batch_alter_table("highlights_topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_highlights_topics_topic_id"), ["topic_id"], unique=False)

    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.alter_column("processing", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("reflections", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("notes", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("done", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("progress", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
        batch_op.alter_column("archived", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("title", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.alter_column("unread", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("uuid", existing_type=sa.UUID(), nullable=True)

    # Convert bookmarks from JSONB back to VARCHAR
    op.execute("ALTER TABLE article ALTER COLUMN bookmarks TYPE varchar USING bookmarks::text")

    # ### end Alembic commands ###
