"""empty message

Revision ID: 70a086beba9a
Revises: 615e34de5588
Create Date: 2020-06-17 13:34:36.722528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a086beba9a'
down_revision = '615e34de5588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unread', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_unread'), ['unread'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_unread'))
        batch_op.drop_index(batch_op.f('ix_article_title'))
        batch_op.drop_column('unread')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
