"""empty message

Revision ID: 72f7b3154cf7
Revises: 7bef8b12e199
Create Date: 2020-08-29 11:50:08.802585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f7b3154cf7'
down_revision = '7bef8b12e199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_topics',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.create_table('tags_highlights',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_highlights')
    op.drop_table('tags_topics')
    # ### end Alembic commands ###
