"""added Comms model

Revision ID: 755e6e328fcf
Revises: 83c88503ad2b
Create Date: 2021-11-14 23:58:38.636851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "755e6e328fcf"
down_revision = "83c88503ad2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("informational", sa.Boolean(), nullable=True),
        sa.Column("educational", sa.Boolean(), nullable=True),
        sa.Column("promotional", sa.Boolean(), nullable=True),
        sa.Column("highlights", sa.Boolean(), nullable=True),
        sa.Column("reminders", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_comms_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comms")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comms")
    # ### end Alembic commands ###
