"""highlight review_date + review_schedule

Revision ID: 785a5e945438
Revises: b146340e0cce
Create Date: 2021-03-22 22:05:30.631952

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '785a5e945438'
down_revision = 'b146340e0cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(),
               existing_nullable=True)

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_schedule', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_column('review_schedule')
        batch_op.drop_column('review_date')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)

    # ### end Alembic commands ###
