"""added preferences column to user model

Revision ID: 7fe237d21a13
Revises: 5f081fc74cd3
Create Date: 2020-09-15 14:37:07.807399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe237d21a13'
down_revision = '5f081fc74cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_preferences'), ['preferences'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences'))
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
