"""added source to highlight

Revision ID: 8287a55072a2
Revises: eb9ea8694722
Create Date: 2023-01-29 15:18:40.253000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8287a55072a2'
down_revision = 'eb9ea8694722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
