"""empty message

Revision ID: 91c7ada4b1c0
Revises: 6c9a91a335e5
Create Date: 2020-06-28 11:38:08.534631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c7ada4b1c0'
down_revision = '6c9a91a335e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_created_date')

    # ### end Alembic commands ###
