"""empty message

Revision ID: 9a5248c9b8e7
Revises: 2f0ddf836d6d
Create Date: 2020-05-25 22:38:57.157188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5248c9b8e7'
down_revision = '2f0ddf836d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('archived', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_topic_archived'), 'topic', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_archived'), table_name='topic')
    op.drop_column('topic', 'archived')
    # ### end Alembic commands ###
