"""drop content_tree from article

Revision ID: 9e8cff309c37
Revises: 6e7be7a417b3
Create Date: 2026-05-01 09:35:23.718213

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9e8cff309c37"
down_revision = "6e7be7a417b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.drop_column("content_tree")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("content_tree", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
