"""added date_read_date 

Revision ID: a544d948cd1b
Revises: 5c5bf645c104
Create Date: 2021-11-28 20:52:31.230691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a544d948cd1b'
down_revision = '5c5bf645c104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_read_date', sa.Date(), nullable=True))
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('date_read_date')

    # ### end Alembic commands ###
