"""added archived field to articles and highlights

Revision ID: a92a257d84d6
Revises: 70a086beba9a
Create Date: 2020-06-21 15:10:23.891852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92a257d84d6'
down_revision = '70a086beba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_archived'), ['archived'], unique=False)

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_highlight_archived'), ['archived'], unique=False)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_title')
        batch_op.create_index(batch_op.f('ix_topic_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_title'))
        batch_op.create_index('ix_topic_title', ['title'], unique=False)

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlight_archived'))
        batch_op.drop_column('archived')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_archived'))
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
