"""added est read time

Revision ID: aa1990e14a6b
Revises: 02388c08dcb2
Create Date: 2021-05-19 09:10:08.136897

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'aa1990e14a6b'
down_revision = '02388c08dcb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
    
        batch_op.drop_column('read_time')

    # ### end Alembic commands ###
