"""added backref to user - comms

Revision ID: ae7646aac3f6
Revises: b1bd350dc073
Create Date: 2021-11-15 02:21:14.844569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae7646aac3f6"
down_revision = "b1bd350dc073"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_comms_comms", type_="foreignkey")
        batch_op.drop_column("comms")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comms", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key("fk_user_comms_comms", "comms", ["comms"], ["id"])

    # ### end Alembic commands ###
