"""last_action user table

Revision ID: b146340e0cce
Revises: 13fb297d3029
Create Date: 2021-03-21 21:48:34.552013

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'b146340e0cce'
down_revision = '13fb297d3029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_action', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_action')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)

    # ### end Alembic commands ###
