"""changed comms to be 1:1 

Revision ID: b1bd350dc073
Revises: 0801537eefe1
Create Date: 2021-11-15 02:13:53.258474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1bd350dc073"
down_revision = "0801537eefe1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comms", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_user_comms_comms"), "comms", ["comms"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_user_comms_comms"), type_="foreignkey")
        batch_op.drop_column("comms")

    # ### end Alembic commands ###
