"""added indexes

Revision ID: bfc4b5f801ff
Revises: 7a6a4bea1570
Create Date: 2021-04-25 11:32:32.127139

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'bfc4b5f801ff'
down_revision = '7a6a4bea1570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_highlight_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_highlight_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('highlights_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_highlights_topics_highlight_id'), ['highlight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_highlights_topics_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tags_highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_highlights_highlight_id'), ['highlight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_highlights_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_add_by_email'), ['add_by_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_add_by_email'), type_='unique')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_user_id'))

    with op.batch_alter_table('tags_highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_highlights_tag_id'))
        batch_op.drop_index(batch_op.f('ix_tags_highlights_highlight_id'))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_user_id'))

    with op.batch_alter_table('highlights_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlights_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_highlights_topics_highlight_id'))

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlight_user_id'))
        batch_op.drop_index(batch_op.f('ix_highlight_article_id'))

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_user_id'))
        batch_op.alter_column('uuid',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)

    # ### end Alembic commands ###
