"""added do_not_review bool to highlight model

Revision ID: cdddbf0edeb6
Revises: 894a4c974216
Create Date: 2021-08-17 15:50:11.156932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdddbf0edeb6'
down_revision = '894a4c974216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('do_not_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_column('do_not_review')

    # ### end Alembic commands ###
