"""empty message

Revision ID: d122055e9a24
Revises: 183d22bdc4e6
Create Date: 2020-06-22 12:22:19.398277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd122055e9a24'
down_revision = '183d22bdc4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_highlight_archived'), ['archived'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.String(length=512), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_title')
        batch_op.create_index(batch_op.f('ix_topic_title'), ['title'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goog_id'), ['goog_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_goog_id'))
        batch_op.drop_index(batch_op.f('ix_user_firstname'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('firstname')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_title'))
        batch_op.create_index('ix_topic_title', ['title'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('goal')

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlight_archived'))
        batch_op.drop_column('archived')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
