"""empty message

Revision ID: da4b4a0ed3d2
Revises: 9a5248c9b8e7
Create Date: 2020-05-29 17:03:18.576579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4b4a0ed3d2'
down_revision = '9a5248c9b8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_archived'), 'tag', ['archived'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.add_column('highlight', sa.Column('note', sa.String(), nullable=True))
    op.create_index(op.f('ix_highlight_note'), 'highlight', ['note'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highlight_note'), table_name='highlight')
    op.drop_column('highlight', 'note')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_archived'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
