"""empty message

Revision ID: db917a433d28
Revises: 21c82ee44b00
Create Date: 2020-06-12 13:59:17.442017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db917a433d28'
down_revision = '21c82ee44b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_first'), 'user', ['first'], unique=False)
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(), nullable=True))
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    op.drop_index(op.f('ix_user_first'), table_name='user')
    op.drop_column('user', 'first')
    # ### end Alembic commands ###
