"""uuid to articles

Revision ID: e07ab0ac88a8
Revises: 4975678132e5
Create Date: 2020-11-24 20:15:45.515065

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'e07ab0ac88a8'
down_revision = '4975678132e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
