"""added bookmarks col to article table

Revision ID: e308ad6026ac
Revises: d34b840ceb83
Create Date: 2021-05-04 14:39:12.238139

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = 'e308ad6026ac'
down_revision = 'd34b840ceb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmarks', sa.String(), nullable=True))

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_index('ix_highlight_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.create_index('ix_highlight_text', ['text'], unique=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('bookmarks')

    # ### end Alembic commands ###
