"""added unique constraints to uuid cols

Revision ID: e5f879371002
Revises: 202c385e6984
Create Date: 2023-02-01 08:06:21.388363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5f879371002"
down_revision = "202c385e6984"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.drop_index("ix_article_uuid")
        batch_op.create_index(batch_op.f("ix_article_uuid"), ["uuid"], unique=True)

    with op.batch_alter_table("highlight", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_highlight_uuid"), ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("highlight", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_highlight_uuid"), type_="unique")

    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_article_uuid"))
        batch_op.create_index("ix_article_uuid", ["uuid"], unique=False)
    # ### end Alembic commands ###
