"""Add separate token fields for API, access, and refresh tokens

Revision ID: f22d4bf926a9
Revises: 26b62ee75c23
Create Date: 2025-12-17 12:26:12.993740

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f22d4bf926a9'
down_revision = '26b62ee75c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('api_token_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('access_token_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_expiration', sa.DateTime(), nullable=True))

    # Migrate existing token data to api_token
    op.execute('UPDATE "user" SET api_token = token, api_token_expiration = token_expiration WHERE token IS NOT NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.create_index(batch_op.f('ix_user_access_token'), ['access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_api_token'), ['api_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_refresh_token'), ['refresh_token'], unique=True)
        batch_op.drop_column('token')
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_user_api_token'))
        batch_op.drop_index(batch_op.f('ix_user_access_token'))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=1)
        batch_op.drop_column('refresh_token_expiration')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token_expiration')
        batch_op.drop_column('access_token')
        batch_op.drop_column('api_token_expiration')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
